### ISSUE TITLE
MAINT: Remaning TODO

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-gui-addons#5]
- [x] Merge https://github.com/mne-tools/mne-gui-addons/pull/3 which adds doc deployment, etc.
- [x] Release 0.1 on GitHub, and manually release on PyPI (needs to be done once to create the package)
- [x] Add PyPI secret for mne-gui-addons so that future releases auto-release
- [x] Check doc deployment: https://mne.tools/mne-gui-addons/
- [x] Get MNE-Python to use mne-gui-addons instead of built in, deprecate MNE code, add to mne sys_info: https://github.com/mne-tools/mne-python/pull/11616
- [x] Move `tutorials/clinical/10_ieeg_localize.py` over to this repo
- [x] Move `examples/preprocessing/locate_ieeg_micro.py` over to this repo
- [x] Add conda-forge infrastructure: https://github.com/conda-forge/staged-recipes/pull/22453

Then I think the workflow will be all set!

**Comment by alexrockhill** [comment]
Does it have to be on `conda-forge` to pass the CIs and open a PR in `mne-python`? Or is that okay to go ahead with?

**Comment by larsoner** [comment]
Yes because we want to test that it actually works with MNE-Python's `environment.yml`

**Comment by larsoner** [comment]
... but if you want to start at the MNE-Python end you can, we just shouldn't merge it until we can add `mne-gui-addons` to `environment.yml` over there

**Comment by larsoner** [comment]
... but `conda-forge` is usually a very quick process, and maintenance burden is very low with `automerge` over there. Once you assent in https://github.com/conda-forge/staged-recipes/pull/22453#pullrequestreview-1367397017 then it'll probably be working in a day or two at most

**Comment by larsoner** [comment]
@alexrockhill if you want I think another doable step is to move `tutorials/clinical/10_ieeg_localize.py` from MNE-Python over to this repo. At the MNE-Python end you can add a redirect to `doc/conf.py` that redirects to this repo's `auto_examples/10_ieeg_localize.html` or whatever.

**Comment by alexrockhill** [comment]
Ok, I can do that once the PR merges

**Comment by larsoner** [comment]
... and `examples/preprocessing/locate_ieeg_micro.py` can also be migrated

**Comment by alexrockhill** [comment]
I can do these PRs but I'm not sure how to redirect the example url, do we do that anywhere else? I think you mentioned it was as just editing the `conf.py`, I can look into that when I get a chance.

**Comment by larsoner** [comment]
https://github.com/mne-tools/mne-python/blob/4eb9ef04c50710dba840ceaac6dc4f69ffefdd31/doc/conf.py#L1242

**Comment by alexrockhill** [comment]
Gotcha thanks, I'll do that ASAP

**Comment by alexrockhill** [comment]
Is this all done?

**Comment by alexrockhill** [comment]
Ok now should be good

**Comment by larsoner** [comment]
Agreed!
